apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.deny-public-nets-egress
spec:
  tier: security
  # label on ns1 namespace
  # namespaceSelector: compliance == "open"
  selector: "projectcalico.org/namespace == 'default' && app == 'centos'"
  order: 100
  types:
    - Egress
  egress:
  - action: Deny
    protocol: TCP
    source: {}
    destination:
      selector: "type == 'public' && list-type == 'cidr'"
  - action: Deny
    protocol: ICMP
    source: {}
    destination:
      selector: "type == 'public' && list-type == 'cidr'"
  # - action: Pass
  #   source: {}
  #   destination: {}
