kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netpolicy-access
rules:
- apiGroups: ["networking.k8s.io","extensions",""]
  resources: ["networkpolicies"]
  verbs: ["get","list","watch"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-netpolicy-access
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: netpolicy-access
  apiGroup: rbac.authorization.k8s.io
---
