kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netpolicy-reader
rules:
- apiGroups: ["networking.k8s.io","extensions",""]
  resources: ["networkpolicies"]
  verbs: ["get","list","watch"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-netpolicy-reader
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: netpolicy-reader
  apiGroup: rbac.authorization.k8s.io
---
