kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ui-needed-listers
rules:
- apiGroups: ["networking.k8s.io","extensions",""]
  resources: ["networkpolicies","namespaces"]
  verbs: ["watch","list"]
- apiGroups: ["projectcalico.org"]
  resources: ["tiers","tier.networkpolicies","tier.globalnetworkpolicies","tier.stagedkubernetesnetworkpolicies","stagedkubernetesnetworkpolicies","globalnetworksets","networksets"]
  verbs: ["watch","list"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ui-traffic-stats
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["calico-node-prometheus:9090", "https:tigera-api:8080"]
  verbs: ["get","create"]
# Access to flow logs, audit logs, and statistics
- apiGroups: ["lma.tigera.io"]
  resources: ["*"]
  resourceNames: ["flows", "audit*", "events", "dns"]
  verbs: ["get"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tier-security-admin
rules:
- apiGroups: ["projectcalico.org"]
  resources: ["tiers"]
  resourceNames: ["security"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["projectcalico.org"]
  resources: ["tier.networkpolicies","tier.globalnetworkpolicies","tier.stagedglobalnetworkpolicies","tier.stagednetworkpolicies","tier.kubernetesnetworkpolicies","tier.stagedkubernetesnetworkpolicies","globalnetworksets","networksets"]
  resourceNames: ["security.*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tier-default-reader
rules:
- apiGroups: ["projectcalico.org"]
  resources: ["tiers"]
  resourceNames: ["default"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["projectcalico.org"]
  resources: ["tier.networkpolicies","tier.globalnetworkpolicies","tier.stagedglobalnetworkpolicies","tier.stagednetworkpolicies","tier.kubernetesnetworkpolicies","tier.stagedkubernetesnetworkpolicies","globalnetworksets","networksets"]
  resourceNames: ["default.*"]
  verbs: ["get", "list", "watch"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-ui-needed-lister
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: ui-needed-listers
  apiGroup: rbac.authorization.k8s.io
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-ui-traffic-stats
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: ui-traffic-stats
  apiGroup: rbac.authorization.k8s.io
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-security-tier-admin
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: tier-security-admin
  apiGroup: rbac.authorization.k8s.io
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sally-default-tier-reader
subjects:
- kind: ServiceAccount
  name: sally
  namespace: default
roleRef:
  kind: ClusterRole
  name: tier-default-reader
  apiGroup: rbac.authorization.k8s.io
