---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: default
  labels:
    app: centos
spec:
  containers:
  - name: centos
    image: centos:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 60; done;" ]
    resources: {}