apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  order: 2000
  selector: "projectcalico.org/namespace == 'ns1' || projectcalico.org/namespace == 'ns2'"
  types:
  - Ingress
  - Egress
